In [1]:
 import numpy as np

## Sorting

In [8]:
# Sort Values 1D Array

data = np.array([310, 34, 23, 11])

print('Sorted Values :', np.sort(data))

Sorted Values : [ 11  23  34 310]


In [15]:
# Sort Values 2D Array

data = np.array([
    
    [310, 34, 23, 11],
    [210, 45, 56, 13]

])


print('Row Wise Sorted Values  :\n', np.sort(data))
print('\n')
print('Column Wise Sorted Values  :\n', np.sort(data, axis=0))


# 0 looks like an egg falling down (Rows).
# 1 looks like a person walking across a bridge (Columns)

Row Wise Sorted Values  :
 [[ 11  23  34 310]
 [ 13  45  56 210]]


Column Wise Sorted Values  :
 [[210  34  23  11]
 [310  45  56  13]]


In [25]:
# Argument Sort (Provide Index No Where Sort Values)
data = np.array([30, 10, 20])

print('Argument Sort :', np.argsort(data))

Argument Sort : [1 2 0]


## Searching

In [27]:
# Find Index No In data
a = np.array([10, 20, 30, 40, 50])
print(np.where(a==30))

(array([2], dtype=int64),)


In [31]:
# Find Index No In data Where Satisfy Condition
a = np.array([10, 15, 20, 25, 30])

print(np.where(a % 2 ==0))

# -------------------------------------------------------------
# Find Index No In data Where Satisfy Condition if Not Exist
a = np.array([10, 15, 20, 25, 30])

print(np.where(a % 2 ==60))

(array([0, 2, 4], dtype=int64),)
(array([], dtype=int64),)


In [34]:
# Where To Put This No That Array Remain Sorted After Add in All Elements Provide Index Number
print(np.searchsorted(a, 24))

3


In [ ]:
|