In [1]:
import numpy as np

In [14]:
arr = np.array([10, 20, 30, 40])

mask = arr > 25

masked_arr = arr[mask]
masked_arr

array([30, 40])

In [24]:
# Direct

arr = np.array([10, 20, 30, 40, 50, 60, 30, 20, 20, 20, 20, 30, 40, 50, 5])

res = arr[arr > 29]
res

array([30, 40, 50, 60, 30, 30, 40, 50])

In [42]:
# And OR Condition also Apply

# And
arr = np.array([10, 20, 300, 400, 500, 60, 30, 20, 20, 20, 20, 30, 40, 50, 5])

res = arr[(arr > 29) & (arr < 300)]
print(f'Result by &(AND) Operation :\n', res)

# Or
arr = np.array([10, 20, 300, 400, 500, 60, 30, 20, 20, 20, 20, 30, 40, 50, 5])

res = arr[(arr > 29) | (arr < 300)]
print(f'\nResult by |(OR) Operation :\n', res)

Result by &(AND) Operation :
 [60 30 30 40 50]

Result by |(OR) Operation :
 [ 10  20 300 400 500  60  30  20  20  20  20  30  40  50   5]


In [47]:
# Experiment on Same 2D Array it Return 1D Array
arr = np.array([[1, 2, 3, 4], [11, 22, 33, 44]])

res = arr[(arr > 3) & (arr < 44)]
res

array([ 4, 11, 22, 33])

In [53]:
# Values Assign with Condition
age = np.array([12, 11, 56, 23, 75, 23, 70, 26, 92, 82, 88])
age[(age < 20) & (age > 10)] += 1


array([13, 12, 56, 23, 75, 23, 70, 26, 92, 82, 88])

In [55]:
# Advance Values Assign with Condition
label = np.where(
    (
        (age > 20)
        &
        (age < 75)
    ),
    
    'Young',
    'other'
)

label

array(['other', 'other', 'Young', 'Young', 'other', 'Young', 'Young',
       'Young', 'other', 'other', 'other'], dtype='<U5')

In [66]:
# Advance Values Assign with Condition
Equality = np.where(
    age < 20, 'Child',
    np.where(age > 75, 'Old', 'Young')
                   )
Equality

array(['Child', 'Child', 'Young', 'Young', 'Young', 'Young', 'Young',
       'Young', 'Old', 'Old', 'Old'], dtype='<U5')

In [68]:
Random = [True, False, True, False, True, False, True, False, True, False, True]

Equality[Random]

array(['Child', 'Young', 'Young', 'Young', 'Old', 'Old'], dtype='<U5')