In [1]:
import numpy as np

In [10]:
arr = np.array([10, 20, 30])

In [11]:
Addition = arr+1000

print(Addition)

[1010 1020 1030]


In [13]:
Subtraction = arr - 5

print(Subtraction)

[ 5 15 25]


In [15]:
Multiplication = arr * 2

print(Multiplication)

[20 40 60]


In [16]:
Division = arr / 2

print(Division)

[ 5. 10. 15.]


In [20]:
Comparision = arr > 14

print(Comparision)

[False  True  True]


In [21]:
Sum = arr.sum()

print(Sum)

60


In [22]:
Mean = arr.mean()

print(Mean)

20.0


In [24]:
arr1 = [90, 20, 15]

Arr_Addition = arr + arr1 # Must Have Same Shape 

print(Arr_Addition)

[100  40  45]
