In [1]:
import numpy as np

In [3]:
# Diffrent Shape and Size Operations = Brodcasting

In [11]:
arr = np.array([x for x in range(1, 7)]).reshape(2, 3)

print('arr :\n', arr)

print('\narr + 10 : \n', arr + 10)

arr :
 [[1 2 3]
 [4 5 6]]

arr + 10 : 
 [[11 12 13]
 [14 15 16]]


In [19]:
a = np.array([2, 4, 6])
print('A :\n', a)

b = np.array([[1, 3, 5], [6, 7, 10]])
print('\nB :\n', b)

Result = a + b
print('\nResult : A + B\n', Result)

A :
 [2 4 6]

B :
 [[ 1  3  5]
 [ 6  7 10]]

Result : A + B
 [[ 3  7 11]
 [ 8 11 16]]


In [29]:
# Numpy Array Where Conditional Pass Fail Check
Score = np.array([6, 9, 0, 7, 6, 4, 2, 5])
Result = ['Fail', 'Pass']

Check_by_Numpy = np.where(Score >= 7 , Result[0], Result[1])
print('Check_by_Numpy :', Check_by_Numpy)

Check_by_Numpy : ['Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']


In [30]:
# Matrix * Vectors
M = np.array([[1, 2],[3, 4]])
V = np.array([10, 20])

Res = M*V
print(Res)


[[10 40]
 [30 80]]
