In [1]:
import numpy as np

# 1. Accross the Columns And Rows (Sum)

In [24]:
arr = np.array([range(1, 3), range(3, 5)])
arr

array([[1, 2],
       [3, 4]])

In [25]:
# Sum All Elements
all_sum = arr.sum()
print(all_sum)

10


In [26]:
# Sum All Rows Elements
row_sum = arr.sum(axis = 1)
print(row_sum)

[3 7]


In [27]:
# Sum All Column Elements
row_sum = arr.sum(axis = 0)
print(row_sum)

[4 6]


# 2. Accross the Columns And Rows (Min, Max)

In [28]:
# Find Maximum Accross the Rows And Columns
max_accross_row = arr.max(axis=1)
print('Max Accross Row :\t', max_accross_row)

max_accross_Columns = arr.max(axis=0)
print('Max Accross Columns :\t', max_accross_Columns)

Max Accross Row :	 [2 4]
Max Accross Columns :	 [3 4]


In [29]:
# Find Minimum Accross the Rows And Columns
min_accross_row = arr.min(axis=1)
print('Max Accross Row :\t', min_accross_row)

min_accross_Columns = arr.min(axis=0)
print('Max Accross Columns :\t', min_accross_Columns)

Max Accross Row :	 [1 3]
Max Accross Columns :	 [1 2]


# 3. Return Index Number

In [34]:
# This Return Index of Minimum Array Element Row Wise
print(arr.argmin(axis=1))

[0 0]


In [36]:
# This Returaxn Index of Maximum Array Element Column Wise
print(arr.argmax(axis=0))

[1 1]


In [ ]:
# This Returaxn Index of Array
arr = np.array([10, 20, 30, 40, 50])

index = np.where(arr == 30)
print(index)

# 4. 3D Array Matric Operations Sum by Depth, Row, Columns

In [56]:
arr = np.array([range(1, 13)])
arr = arr.reshape(2, 2, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
# 3D Array Depth Wise Sum (Over Lap At Each Other and Sum)


print(arr.sum(0))

# Same
# print(np.sum(arr, axis = 0))

[[ 8 10 12]
 [14 16 18]]


In [66]:
# 3D Array Row Wise Sum (Stack both cut and Sum)


print(arr.sum(1))

# Same
# print(np.sum(arr, axis = 1))

[[ 5  7  9]
 [17 19 21]]


In [68]:
# 3D Array Columns Wise Sum (Vertically Fold and Sum)


print(arr.sum(2))

# Same
# print(np.sum(arr, axis = 2))

[[ 6 15]
 [24 33]]


# 5. Keep Dimension as it is Not Change

In [77]:
row_sum = np.sum(arr, axis=1, keepdims=True)

print(row_sum)
print()

col_sum = np.sum(arr, axis=2, keepdims=True)
col_sum

[[[ 5  7  9]]

 [[17 19 21]]]



array([[[ 6],
        [15]],

       [[24],
        [33]]])