In [1]:
import numpy as np

## Stacking

In [40]:
# Array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

### Horizontal Stacking

In [32]:
print('Horizontal Stacking :\n', np.hstack((arr1, arr2))) # Same No of Rows and Dimension

Horizontal Stacking :
 [1 2 3 4 5 6]


### Vertical Stacking

In [37]:
print('Vertical Stacking :\n', np.vstack((arr1, arr2)))

Vertical Stacking :
 [[1 2 3]
 [4 5 6]]


### Columns Stacking

In [38]:
print('Column Stacking :\n', np.column_stack((arr1, arr2)))

Column Stacking :
 [[1 4]
 [2 5]
 [3 6]]


### Rows Stacking

In [39]:
print('Row Stacking :\n', np.row_stack((arr1, arr2)))

Row Stacking :
 [[1 2 3]
 [4 5 6]]


## Split

In [52]:
# Data
Arr_1 = np.array([10, 20, 30, 40, 50, 60])
Arr_2 = np.array([[10, 20, 30, 100], [40, 50, 60, 200]])


#### Split Array In 3 Equal Parts

In [53]:
print('Array Divide In 3 Equal Parts :\n', np.split(Arr_1, 3))      # np.split(array, no_in_Split)

Array Divide In 3 Equal Parts :
 [array([10, 20]), array([30, 40]), array([50, 60])]


#### Horizontally Split Array In 3 Equal Parts

In [60]:
print('Array Horizontally Divide In 4 Equal Parts :\n', np.hsplit(Arr_2, 4))      # np.hsplit(array, no_in_Split)

Array Horizontally Divide In 4 Equal Parts :
 [array([[10],
       [40]]), array([[20],
       [50]]), array([[30],
       [60]]), array([[100],
       [200]])]


#### Vertically Split Array In 3 Equal Parts

In [62]:
print('Array Vartically Divide In 4 Equal Parts :\n', np.vsplit(Arr_2, 2))      # np.vsplit(array, no_in_Split)

Array Vartically Divide In 4 Equal Parts :
 [array([[ 10,  20,  30, 100]]), array([[ 40,  50,  60, 200]])]
