In [1]:
import numpy as np
import pandas as pd

In [6]:
# Indexing in Numpy arr[index_no]

array_a = np.array([1, 2, 3, 4, 5])

print(array_a[0])                    # Get First Element
print(array_a[1])                    # Get Second Element
print(array_a[-1])                   # Get Last Element
print(array_a[-2])                    # Get Second Last Element

# print(array_a[-2435])                    # out of Bounds Errors Show for more then length indexing

1
2
5
4


In [15]:
# Slicing in Numpy  arr[Starting_Element_Index : End_Element_Index+1, Step_Size] # Deafault Step_Size=1
array_a = np.array([10, 20, 30, 40, 50])

print(array_a[1:4])                    # Get Second to Thrid Index Elements  
print(array_a[:4])                     # Get all Elements Start till Thrid Index Elements
print(array_a[1:])                     # Get all Elements from Second Index till last
print(array_a[1:])                     # Get Second to Last Element
print(array_a[1:4:2])                  # Get Second to Thrid Index Elements with 1 Step Gap 
print(array_a[0:-1:2])                  # Get First to last Index Elements with 2 Step Gap


[20 30 40]
[10 20 30 40]
[20 30 40 50]
[20 30 40 50]
[20 40]
[10 30]
