In [1]:
# Array Creation

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([[1, 2],
       [3, 4]])

In [5]:
c = np.array([[[1, 2], [3, 4]], [[5,6], [6,7]]])

In [6]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [6, 7]]])

In [7]:
d = np.array(1)

In [8]:
d

array(1)

In [9]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

# Numpy Dimension
np.ndim(c)

1
2
3
0


3

In [10]:
a = np.array([1, '2', 3])
a

array(['1', '2', '3'], dtype='<U11')

In [11]:
a = np.array([1, True, False])
a


array([1, 1, 0])

In [12]:
a = np.array([True, False, 0])
a


array([1, 0, 0])

In [13]:
a = np.array([1, 2, 3])
a


array([1, 2, 3])

In [14]:
a = np.array([1.1, 1, 3])
a

array([1.1, 1. , 3. ])

In [15]:
a = np.array([1,1,1])
a

array([1, 1, 1])