In [1]:
import numpy as np

In [16]:
# Generate Random Values From 0 to 1 in Float

print('1 Random Value              :', np.random.rand())          # 1 Random Value
print('\n')

print('5 Random Value              :', np.random.rand(5))         # 5 Random Value
print('\n')

print('Random Values in 3*3 Matrix :\n', np.random.rand(3, 3))     # Random Values in 3*3 Matrix 

print('\nRandom Values in 2*3*4 Matrix :\n', np.random.rand(2, 3, 4))  # Random Values in 2*3*4 Matrix 

# 2 (The First Dimension): There are 2 main blocks (often thought of as "matrices" or "pages").
# 3 (The Second Dimension): Each of those 2 blocks contains 3 rows.
# 4 (The Third Dimension): Each row contains 4 columns.

1 Random Value              : 0.15353990148186036


5 Random Value              : [0.84294759 0.64650361 0.67432158 0.62283513 0.94786803]


Random Values in 3*3 Matrix :
 [[0.09692929 0.99688709 0.27651507]
 [0.39338032 0.59981837 0.46516581]
 [0.08794997 0.51203209 0.45911663]]

Random Values in 3*3 Matrix :
 [[[0.2059962  0.9024048  0.1466014  0.03570408]
  [0.45211681 0.99169462 0.72214873 0.65656863]
  [0.22475207 0.29966597 0.67387344 0.49660751]]

 [[0.2207613  0.15277357 0.04696567 0.69536711]
  [0.29423729 0.5123968  0.53670072 0.15574324]
  [0.08797275 0.41435347 0.59875189 0.84648817]]]


In [22]:
# Generate Random Values From 0 to 1 in Integer

print('Random Values From One to 10            :', np.random.randint(1, 10))
print('\n')

print('5 Random Values From One to 10           :', np.random.randint(1, 10, 5))      
print('\n')

print('3*3 Matrics Random Values From One to 10: \n', np.random.randint(1, 10, (3, 3))) 



Random Values From One to 10            : 3


5 Random Values From One to 10           : [5 2 2 3 9]


3*3 Matrics Random Values From One to 10: 
 [[8 5 7]
 [6 4 1]
 [3 4 3]]


In [40]:
# Get Random Choice From Dataset
data = np.array([1, 2, 3, 4, 5, 6])

print('Single Random Value Select From Provided Dataset :', np.random.choice(data))
print('Double Random Value Select From Provided Dataset :', np.random.choice(data, 2))

Single Random Value Select From Provided Dataset : 4
Double Random Value Select From Provided Dataset : [6 3]


In [41]:
# Shuffle Data Randomly
data = np.array([10, 20, 30, 40, 50, 60])

np.random.shuffle(data) 

print(data)

[50 20 40 10 60 30]


In [43]:
# Shuffle Data Randomly and Make New Copy in System
data = np.array([10, 20, 30, 40, 50, 60])

shuffle_data = np.random.permutation(data) 

print(shuffle_data)

[30 60 10 50 20 40]


In [51]:
# Fixed Values Every Time Run 
np.random.seed(42)
print(np.random.randint(1, 10, 5))

[7 4 8 5 7]
