In [2]:
import numpy as np 

Reshaping 1D --> 2D
    2D --> 3D
    3D --> 1D
    Any

# Reshape Muliple = Total Elements in Array

In [20]:
arr = np.array([1, 2, 3, 4])

# Dimension
print('Dimension :\t', arr.ndim)

# Size
print('Size :\t', arr.size)

# Data Type
print('Data Type :\t', arr.dtype)

# Shape
print('Shape :\t', arr.shape)

Dimension :	 1
Size :	 4
Data Type :	 int32
Shape :	 (4,)


In [25]:
# Reshape 2D # arr.reshape(2(1D Array), 2(0D Array)/Each)

arr = np.array([1, 2, 3, 4])
Reshape = arr.reshape(2, 2)
print(Reshape)

[[1 2]
 [3 4]]


In [33]:
# Reshape 3D # arr.reshape(
2(2D Array),
3(1D Array)/Each 2D,
2(0D Array)/Each 1D
)

arr = np.array([x for x in range(1, 13)])
Reshape = arr.reshape(2, 3, 2)
print(Reshape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [38]:
# Same For 4D Array 
# (
#     4(3D),
#     3(2D),
#     2(1D),
#     1(0D)
# )
arr = np.array([x for x in range(1, 25)])
Reshape = arr.reshape(4, 3, 2, 1)
print(Reshape)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [18]]]


 [[[19]
   [20]]

  [[21]
   [22]]

  [[23]
   [24]]]]


In [48]:
# Numpy Automatically Set the Data By -1 At That Place

arr = np.array([x for x in range(1, 13)])

arr_3D = arr.reshape(-1, 2, 2)
print('\narr_3D \n', arr_3D)


arr_2D = arr.reshape(2, -1, 2)
print('\narr_2D \n', arr_2D)


arr_1D = arr.reshape(2, 2, -1)
print('\narr_1D \n', arr_1D)


arr_3D 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

arr_2D 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

arr_1D 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [58]:
# Convert Any Array to 1D by -1
arr = np.array(
    [[[1,2],
  [3,4]],
       
 [[5, 6],
  [7, 8]],
       
 [[9, 10],
  [11, 12]]]
)
print('Shape of Array :', arr.shape)

arr_1D = arr.reshape(-1)
print(arr_1D)  # Convert This in 1D Array

Shape of Array : (3, 2, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [60]:
# Convert Horizontal Data in Vertical data by (-1, 1)
print(arr_1D.reshape(-1, 1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
